name: go-ratelimiter
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build-tools:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        go-version: [ 1.16.x, 1.17.x, 1.18.x ]
    runs-on: ${{ matrix.platform }}
    name: Unit test
    steps:
      - name: Cancel previous builds
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-test-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-test-
            ${{ runner.os }}-go-

  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        go-version: [ 1.16.x, 1.17.x, 1.18.x ]
    runs-on: ${{ matrix.platform }}
    name: Unit test
    steps:
      - name: Cancel previous builds
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-test-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-test-
            ${{ runner.os }}-go-
      - name: Unit tests
        run: make test-cover

      - name: Upload coverage report
        uses: codecov/codecov-action@v4.1.1
        with:
          file: ./coverage.out

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous builds
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-test-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-test-
            ${{ runner.os }}-go-
      - name: go-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: 'v1.45.2'
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true